# Generated by Django 5.0.6 on 2024-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('kakao_id', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('alarm_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('post_id', models.BigIntegerField()),
                ('sender_id', models.BigIntegerField()),
                ('receiver_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reviewer_id', models.BigIntegerField()),
                ('reviewee_id', models.BigIntegerField()),
                ('score', models.FloatField()),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('kakao_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('nickname', models.CharField(default='unknown', max_length=20)),
                ('student_id', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('user_comment', models.TextField(blank=True, default='각오 한마디', null=True)),
                ('user_capacity', models.TextField(blank=True, default='들은 과목과 기술 스택, 관심사를 적어주세요.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
