# Generated by Django 5.0.6 on 2024-07-08 10:38

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('kakao_id', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('student_id', models.IntegerField(default=None, unique=True)),
                ('skill_id', models.IntegerField(blank=True, null=True, verbose_name=home.models.Skills)),
                ('user_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_taken_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='courses_taken', to='home.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('content', models.TextField(blank=True, null=True)),
                ('reviewee_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviewees', to='home.users')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviewers', to='home.users')),
            ],
        ),
    ]
