# Generated by Django 5.0.6 on 2024-07-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewee_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewer_id',
            field=models.BigIntegerField(),
        ),
    ]
