# Generated by Django 5.0.6 on 2024-07-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='course_taken_id',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='skill_id',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='student_id',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='users',
            name='user_comment',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
