# Generated by Django 5.0.6 on 2024-07-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_users_user_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_capacity',
            field=models.TextField(blank=True, default='들은 과목과 기술 스택, 관심사를 적어주세요.', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_comment',
            field=models.TextField(blank=True, default='각오 한마디', null=True),
        ),
    ]
