# Generated by Django 5.0.6 on 2024-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_users_course_taken_id_users_skill_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='course_taken_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='skill_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='student_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
