# Generated by Django 5.0.6 on 2024-07-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_users_user_capacity_alter_users_user_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('alarm_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='home.users')),
            ],
        ),
    ]
