# Generated by Django 5.0.6 on 2024-07-08 08:24

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_course_taken_id_alter_users_skill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='skill_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=home.models.Skills),
        ),
        migrations.AlterField(
            model_name='users',
            name='student_id',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='course_taken_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='courses_taken', to='home.courses'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('content', models.TextField(blank=True, null=True)),
                ('reviewee_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviewees', to='home.users')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reviewers', to='home.users')),
            ],
        ),
    ]
