# Generated by Django 5.0.6 on 2024-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_users_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('course_name', models.CharField(max_length=20)),
            ],
        ),
    ]
