# Generated by Django 5.0.6 on 2024-07-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_courselist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='course_id',
            new_name='course_code',
        ),
    ]
