# Generated by Django 5.0.6 on 2024-07-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takencourses',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='usersskills',
            name='skill_code',
        ),
        migrations.RemoveField(
            model_name='takencourses',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usersskills',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='TakenCourses',
        ),
        migrations.DeleteModel(
            name='UsersSkills',
        ),
    ]
