# Generated by Django 5.0.6 on 2024-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.BigIntegerField()),
                ('course_id', models.CharField(max_length=10)),
                ('leader_id', models.BigIntegerField()),
                ('is_full', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.BigIntegerField(default=None)),
                ('member_id', models.BigIntegerField(default=None)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=10)),
                ('leader_id', models.BigIntegerField()),
                ('post_content', models.TextField(blank=True, null=True)),
                ('member_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.BigIntegerField()),
                ('leader_id', models.BigIntegerField()),
                ('member_id', models.BigIntegerField()),
                ('request_comment', models.TextField(blank=True, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
