# Generated by Django 5.0.6 on 2024-07-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
